### PR TITLE
swap rapply and rapply'

### PR DESCRIPTION
**Pull request by mikeshulman**

### CODE REVIEW

**Comment by JasonGross** [comment]
Can you include a timing diff of the whole library, to make sure this isn't unintentionally slowing some things down?

Otherwise, LGTM

**Comment by mikeshulman** [comment]
Timing diff added (though github seems to be wrapping it uglily?).

**Comment by spitters** [comment]
LGTM. Do you want to bring it up on coq-dev too?

**Comment by mikeshulman** [comment]
I'm not on coq-dev, but anyone who is, feel free.

**Comment by mikeshulman** [comment]
I saw two LGTMs, and I included the timing diff showing no significant change in speed, so I'm going to merge.

**Pull request merged**
