### PR TITLE
Reduce universe variables in V.v

### PR DESCRIPTION
**Pull request by jdchristensen**
Closes: #620 

See issue #620 for a discussion of this.  In the past, some definitions in the file HIT/V.v used tens of thousands of universe variables.  It seems like Coq has to a large degree fixed this:  with Coq 8.16, I randomly checked a number of definitions, and the worst I found were:  `V_func` (219 universe variables), `V_union` (219 universe variables) and `infinity` (64).  (Did I miss any that are worse?)

I found that annotating the definition of just one function, `V_ind`, greatly improved things.  Now those three definitions use 3, 3 and 6 universe variables, respectively.  Also, the build time goes from 1.35s to 0.96s on my system.

I also annotated the definition of `V` a bit more, but there is no change to the meaning.  This just documents and enforces the existing universe variables.

One note:  it's possible to get rid of the universe variable `U'` in the definition of `V`, which would make it land in the successor universe `Type@{U+1}`.  But since we can't use successor universes in other situations, we still need `U'` for most or all of the remaining definitions in the file.  So I left it in `V` as well, for consistency.

### CODE REVIEW

**Comment by jdchristensen** [comment]
Oh, I now see that `function` was explicitly mentioned in #620.  With the change to `V_ind`, `function` went from 279 universe variables to 3.

**Comment by jdchristensen** [comment]
I also just noticed that there was an unneeded `fun _ _ =>` in the definition of `V_ind`.  Removing it speeds up the build time from 0.96s to 0.93s.

BTW, someone should check that the universe annotations in `V_ind` are reasonable.  I partly guessed, and then just checked that the library builds, but it's possible that some greater generality could be useful.

**Comment by jdchristensen** [comment]
Tagging @jledent , who last made relevant changes to `V_ind`.

**Comment by SkySkimmer** [comment]
>I also just noticed that there was an unneeded fun _ _ => in the definition of V_ind. Removing it speeds up the build time from 0.96s to 0.93s.

I believe it's there because otherwise it may be possible to get around the need for the truncation hypotheses.
See also https://github.com/HoTT/HoTT/issues/122#issuecomment-22835748
Because there is a fixpoint in this case I'm not sure if the issue applies though.

**Comment by jdchristensen** [comment]
This might be a holdover from a previous version.  Back in 2014, the end looked like:
```
: forall v : V, P v
:= fix F (v : V) :=
     (match v with
      | set A f => fun _ _ => H_set A f (fun a => F (f a))
     end) H_setext H_0trunc.
```
and in master the whole thing is a Fixpoint, which ends with:
```
: P v
:= (match v with
     | set A f => fun _ _ => H_set A f (fun a => V_ind P H_0trunc H_set H_setext (f a))
    end) H_setext H_0trunc.	
```
This PR uses:
```
: P v
:= (match v with
     | set A f => H_set A f (fun a => V_ind P H_0trunc H_set H_setext (f a))
    end).
```
which might be safe because `H_setext` and `H_0trunc` are used in the recursive call.  But I'm not sure.

I can revert this part, unless someone knows that it is safe.  I shouldn't have mixed different issues in this PR.

**Comment by jdchristensen** [comment]
I did check that things like 
```
Definition V_ind_eq@{U' U u | U < U'} `{Funext} (P : V@{U' U} -> Type@{u})
  (H_0trunc : forall v : V@{U' U}, IsTrunc 0 (P v))
  (H_0trunc' : forall v : V@{U' U}, IsTrunc 0 (P v))
  (H_set : forall (A : Type@{U}) (f : A -> V) (H_f : forall a : A, P (f a)), P (set f))
  (H_setext : forall (A B : Type@{U}) (R : A -> B -> HProp@{U}) (bitot_R : bitotal R)
    (h : SPushout R -> V) (H_h : forall x : SPushout R, P (h x)),
    transport@{U' u} _ (setext R bitot_R h) (H_set A (h o spushl R) (H_h oD spushl R))
      = H_set B (h o spushr R) (H_h oD spushr R) )
  (v : V)
  : V_ind P H_0trunc H_set H_setext v = V_ind P H_0trunc' H_set H_setext v
  := idpath.
```
fail, and similarly with a second `H_setext'` argument, but I don't know if that is enough to avoid the inconsistency.

**Comment by mikeshulman** [comment]
It's great that a single universe annotation improves things that much!  That part of this LGTM.

I don't really know about the `fun _ _ =>`.  If no one else is sure either, maybe leave that change out?  0.03s isn't much.

**Comment by jdchristensen** [comment]
Ok, I have dropped that commit and force pushed.  I also added a comment explaining why the universes are annotated and warning anyone who changes them in the future to be careful.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
The dpdgraph error can be ignored. Something needs to be tweaked there.

**Pull request merged**
