### PR TITLE
Torus is equivalent to product of circles and cubical library

### PR DESCRIPTION
**Pull request by Alizter**
This is my second attempt at getting #1053 to work. I have spent some time debugging it and I see that isequiv_cu_path in Cubical/Cube.v is the culprit. I couldn't reopen my previous PR since I force-pushed to this one.

I can't see any reason why proviola gets stuck however. If you comment out everything after and including intros [] near line 100 and stick an admitted there proviola is fine.

### CODE REVIEW

**Comment by Alizter** [comment]
@JasonGross What do you think?

**Comment by Alizter** [comment]
Should I leave the proof as admitted just to make travis happy?

**Comment by mikeshulman** [comment]
We shouldn't keep admits around in the main branch of the library, if that's what you're asking.

**Comment by JasonGross** [comment]
If you replace `intros [].` with `intro x; destruct x` or similar, does that fix the issue with proviola?

**Comment by Alizter** [comment]
OK I can't get this to work anymore. I will close this PR and try again later.

**Pull request closed without merging**
