### PR TITLE
Surreals: [No] is a letin so has no polymorphic universes

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by Alizter** [comment]
Has this always been the case or was something changed in coq 8.10 (or before)?

**Comment by spitters** [comment]
LGTM, but shouldn't (or can't) the type checker give a warning about this?

**Comment by SkySkimmer** [comment]
It will be an error after https://github.com/coq/coq/pull/11978

**Comment by spitters** [comment]
Thanks! Is this the only place in the hott library where this will raise an error?

**Comment by SkySkimmer** [comment]
yes

Gaëtan Gilbert

**Comment by mikeshulman** [comment]
Can someone actually explain what's going on here please?

**Comment by SkySkimmer** [comment]
`No` is a section letin `Let No := GenNo S.` but for some reason it was used as `No@{i}` which makes no sense.

**Comment by mikeshulman** [comment]
Why does it make no sense?

**Comment by JasonGross** [comment]
In Coq `let`-binders cannot be universe-polymorphic.  (One reason is that if they were, then clearing the body of a `let`-binder would result in a lambda with non-prenex universe polymorphism, which is not supported.)  So the universes get fixed at `Let` declaration time.  If you want this to not happen, I think you can use `Notation` instead.

**Comment by mikeshulman** [comment]
Ah, I see, thanks.  It still ends up polymorphic after the section is closed, but the universe is fixed for the entire section; right?

**Comment by JasonGross** [comment]
Yes

**Pull request merged**
