### PR TITLE
Hopefully fix npm issue

### LINKED ISSUE #1318: CI getting stuck due to npm problems
The CI is getting stuck:

```
Run sudo apt-get install -y --allow-unauthenticated npm aspcud ghc cabal-install graphviz xsltproc python-lxml python-pexpect libxml2-dev libxslt1-dev time ocaml camlp5 camlp4 ocaml-findlib libocamlgraph-ocaml-dev lua5.1
Reading package lists...
Building dependency tree...
Reading state information...
time is already the newest version (1.7-25.1build1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: node-gyp (>= 0.10.9) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
##[error]Process completed with exit code 100.
```

I don't know what is causing this or how we can fix it. @JasonGross any ideas?

### PR DESCRIPTION
**Pull request by JasonGross**
As per
https://bugs.launchpad.net/ubuntu/+source/npm/+bug/1809828 and
https://askubuntu.com/a/1092849/223605.  Closes #1318

I haven't tested this, but let's see if it works

### CODE REVIEW

**Comment by jdchristensen** [comment]
The last build (coq master) failed but the first six succeeded.  I restarted them to see if it was a one-off glitch.  The error didn't seem related to the original issue.

**Comment by jdchristensen** [comment]
Hmm, the last job failed again, the same way as the previous time.

**Comment by JasonGross** [comment]
The issue with master is https://github.com/coq/coq/issues/12115, and unrelated to this PR

**Comment by jdchristensen** [comment]
Good, so let's commit this so that we can get my other PR tested and committed.

**Pull request merged**
