### PR TITLE
Update coq submodule

### PR DESCRIPTION
**Pull request by JasonGross**
As per #883, we are tracking Coq master with our master branch.  I've updated coq-dpdgraph to the latest commit on its coq-trunk branch, and updated coq-scripts to its latest commit (because why not?).  This will
hopefully fix the issues we've been having recently with graphs on Travis, though I haven't looked into them much.  (I'm a bit worried that one of the failures to build seems to be a result of cabal not being able to resolve dependencies for the packages we're looking for...)

### CODE REVIEW

**Comment by spitters** [comment]
LGTM, in that I don't see anything strange and I trust @JasonGross in this.
I'm surprised we are still supporting all these old versions, but then again, why not.

**Comment by JasonGross** [comment]
@spitters It's closer to "I don't want to update the code every time a new version comes out" than "I want to support old versions"

**Comment by mikeshulman** [comment]
LGTM, thanks!  I hope it makes Travis happy.

**Comment by JasonGross** [comment]
Updating the version of Haskell's graphviz we ask for seems to have fixed the issue with cabal.

**Pull request merged**
