### PR TITLE
Give better types to pushout operations (hide construction as coeq)

### PR DESCRIPTION
**Pull request by mikeshulman**

### CODE REVIEW

**Comment by spitters** [comment]
LGTM

**Comment by SimonBoulier** [comment]
This is very nice. I had never understood why it was done this way.

**Comment by mikeshulman** [comment]
Rebased, and now updated all the files that use Pushout.v to the new conventions.

**Comment by Alizter** [comment]
Why isn't this merged yet?

**Comment by mikeshulman** [comment]
Well, up until a week ago it couldn't be merged because it was broken.  If @spitters original ack still counts, we need one more maintainer to approve it.

**Comment by spitters** [comment]
Taking @SimonBoulier s message as an ack

**Pull request merged**
