### PR TITLE
some stubby cubical stuff

### PR DESCRIPTION
**Pull request by mikeshulman**
In partial response to #978, here are some lemmas about squares and cubes that I started working on a while ago.  They're very incomplete because I had a specific purpose in mind at the time rather than setting out to write a complete library for squares and cubes, but I did try to choose relatively predictable names for the lemmas and their arguments at least.

If this seems to be a worthwhile starting point, we could merge it and then others could work on improving and adding to it (i don't have the time to work on it further myself right now) -- that would probably be easier than trying to develop it it a branch or a fork and only merging it when it looks more complete.  It compiles and doesn't affect any existing code (so using it is completely optional).

### CODE REVIEW

**Comment by Alizter** [comment]
I had a go redefining the definitions in Square.v using the interval type instead, but it seems to be more work. Perhaps if we wrote some clever tactics for dealing with it? 

A possible advantage of using interval with some clever tactics is that it will allow us to reason about higher cubes without writing them down explicitly.

I also tried labeling the points with a function `Bool -> Bool -> A` but this got tedious quickly. However the paths then become homotopies etc. which may be useful.

**Comment by mikeshulman** [comment]
True cubical type theory uses an interval, but in Book HoTT the interval isn't useful for much; instead we generally define paths, squares, etc. as inductive families.

**Comment by Alizter** [comment]
I am in favour of merging this at the moment. I think the dependent paths will be very useful.

**Comment by mikeshulman** [comment]
Anyone else have a thought about merging this now (pro or con)?

**Comment by mikeshulman** [comment]
Rebased.

**Comment by Alizter** [comment]
@spitters We can merge this too if you are happy with it.

**Pull request merged**
