### PR TITLE
Generalized surreal numbers parametrized by option sorts

### PR DESCRIPTION
**Pull request by mikeshulman**
Basically, you can get a "notion of surreal numbers" by restricting the types parametrizing the left and right options in any way you like, and the basic theorems about order are completely unaffected, while addition and so on do just fine as long as the option sorts are closed under the appropriate operations.  In particular, this includes the plump ordinals from Exercise 11.17 in the book.  All kinds of generalized surreal numbers embed into the "maximal" surreal numbers, though I don't know of a good way to define their images intrinsically.  Finally, and interestingly, *every* surreal number is equal to one whose option sorts are decidable (i.e. either it has no left options or it has a left option, and either it has no right options or it has a right option).

### CODE REVIEW

**Comment by mikeshulman** [comment]
Oh, and the timing diff for this entire changeset starts out

```
After    | File Name                                                 | Before   || Change   
--------------------------------------------------------------------------------------------
4m27.16s | Total                                                     | 4m25.59s || +0m01.56s
--------------------------------------------------------------------------------------------
0m05.67s | Spaces/No/Core                                            | 0m03.72s || +0m01.94s
0m03.00s | Spaces/No/Addition                                        | 0m01.50s || +0m01.50s
```

and then degenerates into noise.  So the extra typeclass inference is not adding hardly any noticeable overhead.

**Comment by mikeshulman** [comment]
I don't really understand the timing diffs for this.  Here's the diff for be830d17db, which I would expect to have all the effect of the extra typeclass inference:

```
After    | File Name                                                 | Before   || Change   
--------------------------------------------------------------------------------------------
4m25.55s | Total                                                     | 4m26.11s || -0m00.55s
--------------------------------------------------------------------------------------------
0m02.98s | Spaces/No/Addition                                        | 0m01.52s || +0m01.46s
0m32.84s | Spaces/BAut/Bool                                          | 0m33.66s || -0m00.81s
0m18.80s | Categories/Category/Sigma/Univalent                       | 0m19.15s || -0m00.34s
0m11.27s | Algebra/ooGroup                                           | 0m11.41s || -0m00.14s
0m10.24s | Comodalities/CoreflectiveSubuniverse                      | 0m10.50s || -0m00.25s
0m08.78s | contrib/Freudenthal                                       | 0m08.88s || -0m00.10s
0m08.05s | Modalities/ReflectiveSubuniverse                          | 0m07.89s || +0m00.16s
```

It seems that the typeclass inference is not slowing down `No/Core` but it is slowing down `No/Addition`... and yet there is enough timing noise in totally unrelated files to cancel out that slowdown?

**Comment by mikeshulman** [comment]
Hmm, okay, running it again the noise goes the other way, but the slowdown in `No/Addition` remains constant, plus a more minor slowdown in `No/Core` is also noticeable:

```
After    | File Name                                                 | Before   || Change   
--------------------------------------------------------------------------------------------
4m28.05s | Total                                                     | 4m25.90s || +0m02.14s
--------------------------------------------------------------------------------------------
0m03.02s | Spaces/No/Addition                                        | 0m01.52s || +0m01.50s
0m33.41s | Spaces/BAut/Bool                                          | 0m33.65s || -0m00.24s
0m19.06s | Categories/Category/Sigma/Univalent                       | 0m19.08s || -0m00.01s
0m11.35s | Algebra/ooGroup                                           | 0m11.33s || +0m00.01s
0m10.48s | Comodalities/CoreflectiveSubuniverse                      | 0m10.56s || -0m00.08s
0m08.88s | contrib/Freudenthal                                       | 0m09.02s || -0m00.13s
0m07.79s | Modalities/ReflectiveSubuniverse                          | 0m07.96s || -0m00.16s
0m07.29s | Pointed                                                   | 0m07.36s || -0m00.07s
0m07.24s | Spaces/BAut/Rigid                                         | 0m07.25s || -0m00.00s
0m07.20s | Spaces/Finite                                             | 0m07.20s || +0m00.00s
0m06.48s | Spaces/BAut                                               | 0m06.48s || +0m00.00s
0m05.75s | Categories/Adjoint/Pointwise                              | 0m05.78s || -0m00.03s
0m05.68s | Idempotents                                               | 0m05.65s || +0m00.02s
0m05.51s | HIT/Colimits/Flattening                                   | 0m05.50s || +0m00.00s
0m05.04s | Modalities/Lex                                            | 0m04.96s || +0m00.08s
0m04.19s | Modalities/Topological                                    | 0m04.17s || +0m00.02s
0m04.12s | Categories/Adjoint/Functorial/Laws                        | 0m04.02s || +0m00.10s
0m04.00s | Spaces/No/Core                                            | 0m03.68s || +0m00.31s
```

Suggestions for speedup are welcome, though it's only a couple seconds in total.

**Comment by SkySkimmer** [comment]
On my machine specifically the `Definition plus_cut` goes from 0.4s to 1.7s.
I don't think it's because of typeclasses, `Typeclasses eauto := debug.` only shows
```
Debug: 1: looking for (InSort S L R) with backtracking
Debug: 1.1: exact Sx on (InSort S L R), 0 subgoal(s)
Debug: 2: looking for (InSort S L' R') with backtracking
Debug: 2.1: exact Sy on (InSort S L' R'), 0 subgoal(s)
Debug: 3: looking for (HasAddition S) without backtracking
Debug: 3.1: exact H0 on (HasAddition S), 0 subgoal(s)
Debug: 4: looking for (InSort S L R) without backtracking
Debug: 4.1: exact Sx on (InSort S L R), 0 subgoal(s)
Debug: 5: looking for (InSort S L' R') without backtracking
Debug: 5.1: exact Sy on (InSort S L' R'), 0 subgoal(s)
plus_cut is defined
Finished transaction in 1.668 secs (1.624u,0.008s) (successful)
```

**Comment by mikeshulman** [comment]
Well, it may not be literally spending the time in typeclass inference, but the only thing that changed in that commit was the use of a typeclass, so it must somehow be indirectly connected, no?

**Comment by mikeshulman** [comment]
If no one has any speedup suggestions, maybe we could go ahead and merge this and put "speed it up" as a to-do item for later?

**Comment by spitters** [comment]
LGTM.

**Comment by JasonGross** [comment]
> Hmm, okay, running it again the noise goes the other way,

Note that there are `-only-diff` versions of the timing scripts, which exclude files that don't depend on the ones that you changed, and therefore have less noise in the overall time.

I'm looking into the timing change now.

**Comment by mikeshulman** [comment]
Thanks.  (FWIW I think the timing scripts could be better documented, and maybe have an easier interface to use and remember; I can never remember which script is which or the name of the variable `PREV_COMMIT` or whatever it is.)

**Comment by JasonGross** [comment]
> FWIW I think the timing scripts could be better documented, and maybe have an easier interface to use and remember

I've updated the `pretty-timed-*diff-tip.sh` files' documentation at the top to mention `PREV_COMMIT`.  Further concrete suggestions and contributions welcome.  (I'm not entirely sure what a better interface would be, or what better documentation would look like.)

**Comment by JasonGross** [comment]
> On my machine specifically the `Definition plus_cut` goes from 0.4s to 1.7s.

Inferring the argument `Sx` to `plus_inner_cut` takes around 0.6 to 1.0 seconds.  Adding `(Sx:=Sx)` to `plus_inner_cut` in `plus_cut` drops the time from 1.445 s to 0.391 s on my machine.

Regarding `No/Core.v`, the line `apply IHL0, No_decode_le.` takes 0.8 seconds.  If you replace it with `apply IHL0, (@No_decode_le _).`, it takes only 0.003 seconds.  I found this line by using `etc/coq-scripts/timing/make-both-single-timing-files.py` on the `theories/Spaces/No/Core.timing` files created by running make with each of the two states I was comparing checked out.

I think that should take care of most of your timing differences.

**Comment by mikeshulman** [comment]
Thanks!  I implemented those changes.

**Pull request merged**
