### PR TITLE
moved Axioms to new directory

### PR DESCRIPTION
**Pull request by Alizter**
as suggested in #1511

### CODE REVIEW

**Comment by jdchristensen** [comment]
If we keep those files, this LGTM.  But do we really need them?

**Comment by Alizter** [comment]
For the library, no. But we would like to make it easier for people to use axioms in their own developments. Making them parameterize everything by the axioms is unnecessary IMO.

Also it has the advantage of "just working" without needing to understand how the axioms are actually set up.

**Comment by jdchristensen** [comment]
It's not clear to me that needing to remember that you have to type:
```coq
Require Import HoTT.Axioms.UnivalenceAxiom.
```
is any simpler than remembering that you have to type:
```coq
Axiom univalence_axiom : Univalence.
Global Existing Instance univalence_axiom.
```
which just fits in with what you would do anytime you want to assume something.  And having additional files in the tree just makes it a bit harder to find things you are looking for.  There's also the point about having multiple witnesses of Univalence, but I'm not sure why that would be a problem.  Anyways, if people think these files are handy, that's fine, but I wonder if there is a single example of anyone using them anywhere.

**Comment by mikeshulman** [comment]
It would be nice to know whether anyone is actually using these files.  But it doesn't do any harm to keep them.

**Comment by mikeshulman** [comment]
I suppose we could delete them and see if anyone complains...

**Comment by jdchristensen** [comment]
It doesn't really matter to me.  I'm just in a "spring cleaning" mood!  :-)

**Comment by SkySkimmer** [comment]
I think the idea is that if 2 files want a global axiom they should get the same one, especially if some 3rd file uses both.

**Comment by Alizter** [comment]
A search on GitHub indicates that it is being used by at least a few:
https://github.com/search?l=Coq&p=2&q=UnivalenceAxiom&type=Code

**Comment by mikeshulman** [comment]
Good to know, thanks.  I probably vote for keeping them, then.

**Comment by jdchristensen** [comment]
I agree.

**Pull request merged**
