### PR TITLE
Make trivial instances explicit

### PR DESCRIPTION
**Pull request by maximedenes**
This is in preparation for coq/coq#9274.

Should be backward compatible but that remains to be tested.

### CODE REVIEW

**Comment by Alizter** [comment]
What is going on here? Can you add some more explanation?

**Comment by SkySkimmer** [comment]
When a class has no content, such as
~~~coq
Class IsTerminalCategory (C : PreCategory)
      `{Contr (object C)}
      `{forall s d, Contr (morphism C s d)} := {}.
~~~
then `Instance : IsTerminalCategory C.` will define it without opening a proof (assuming it manages to fill the implicit arguments of the type). To make it easier to predict when proofs are opened, we are planning to change this behaviour.

**Comment by maximedenes** [comment]
The two errors I get seem unrelated:
```
camlp5 macro files not supported anymore, please port searchdepend.ml4 to coqpp
```
and
```
make[1]: *** No rule to make target `grammar/grammar.cma'.  Stop.
```

is HoTT's CI working properly?

**Comment by JasonGross** [comment]
#988 fixes the CI.  Until that is merged, we expect dpdgraph to fail.  (If 8.9.0 is not going to be actually released soon, or if the tag is going to change, we could merge the bits of that PR that fix the CI without merging the version bump.)

**Comment by JasonGross** [comment]
The issue with master is half Coq's fault; there is still no install target for coqlight (https://github.com/coq/coq/issues/5272), and I guess `grammar/grammar.cma` recently got replaced by something else on master?  (What did it get replaced by?)

**Pull request merged**
