### PR TITLE
Basic theory of commutative rings + some algebra organization

### PR DESCRIPTION
**Pull request by Alizter**
Here is some basic theory of commutative rings. While we were developing this we reorganised the Algebra folder.

Reviewing this may take some time since there are a lot of changes. The main changes are in the Algebra folder which now looks like:
```
theories/Algebra/ooGroup.v
theories/Algebra/Aut.v
theories/Algebra/ooAction.v

theories/Algebra/Congruence.v

theories/Algebra/Rings.v
theories/Algebra/Rings/CRing.v
theories/Algebra/Rings/Ideal.v
theories/Algebra/Rings/QuotientRing.v
theories/Algebra/Rings/Z.v

theories/Algebra/AbGroups.v
theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/AbGroups/Abelianization.v
theories/Algebra/AbGroups/Z.v

theories/Algebra/Groups.v
theories/Algebra/Groups/Group.v
theories/Algebra/Groups/Subgroup.v
theories/Algebra/Groups/QuotientGroup.v
theories/Algebra/Groups/Image.v
theories/Algebra/Groups/Kernel.v
```

Changes outside of the algebra folder include:
 * Compatibility changes in various files to work with new algebra library. Mostly in Homotopy.
 * More lemmas about integers and positive naturals in order to give full ring structure of Z.

We have some really slow performance closing the proof of the first isomorphism theorem for rings, which can be found in Algebra/Rings/QuotientRing.v. It is not typeclass related. I am not really sure what is going on there.

I am making this a draft pull request as there are parts that can be improved.

I would like to thank @jcommelin for working on this with me.

### CODE REVIEW

**Comment by spitters** [comment]
Nice. It would be nice to connect this to the existing first isomorphism theorem in universal algebra which was already formalized by @andreaslyn

**Comment by Alizter** [comment]
@mikeshulman @jdchristensen Anybody able to review this?

**Comment by jdchristensen** [comment]
Sorry, this is a lot to try to go through and I've just been too busy.  Maybe you could point out the parts that you think need close review, and then maybe we could split the work over a couple of reviewers?

**Comment by mikeshulman** [comment]
E.g., which files are new and which are just moved around?

**Comment by Alizter** [comment]
The stuff in Algebra/Rings is all new. Algebra/AbGroups and Algebra/Groups are just rearrangements of of the old files AbelianGroup.v and Group.v.

I also changed the definition of Group from class to a record since it was causing coq to typeclass search in some proofs when it really doesn't need to.

The only part I am unsure about in this PR is in Rings/QuotientRing.v. The first isomorphism theorem for rings is very slow and I could not work out why.

**Comment by Alizter** [comment]
I'm closing this as there is no real way for it to be reviewed meaningfully. I don't really know what I was hoping. I will try to break it up over the next few weeks.

**Pull request closed without merging**
