### PR TITLE
Binary naturals

### PR DESCRIPTION
**Pull request by abooij**
I have implemented a variant on binary naturals, that I learned from Martín Escardó and Cory Knapp, given directly as one inductively defined type.
```coq
Inductive binnat : Type :=
| bzero   :           binnat  (* zero *)
| double1 : binnat -> binnat  (* 2n+1 *)
| double2 : binnat -> binnat. (* 2n+2 *)
```
This allows doing computations with larger naturals than the unary presentation.

I have placed the code in `Classes/implementations`. Feedback is very welcome as I don't consider myself a Coq expert at all.

### CODE REVIEW

**Comment by spitters** [comment]
Thanks. This looks nice.
I have the impression that you may be able to obtain the semiring axioms from univalence, as we already have them for the unaries (I hope).

**Comment by SkySkimmer** [comment]
It should be doable using stuff from Classes/isomorphisms/rings.v

Gaëtan Gilbert

**Comment by abooij** [comment]
@spitters: Indeed I proved the semiring axioms from the fact that the unary naturals satisfy them. See e.g. `binnat_add_assoc`, `binnat_distr_l`, `binnat_full` and `binnat_toR_unique`. However, some things I proved directly since they are computationally relevant, such as the semiring operations, `binnat_dec : DecidablePaths binnat`, and `binnat_trichotomy : Trichotomy (lt : Lt binnat)` (even though the latter are propositions).

**Comment by mikeshulman** [comment]
Interesting!  If we had a computing univalence like in cubical TT, of course, we could use univalence everywhere.  How did you decide which hprops are "computationally relevant" and which are not?

**Comment by mikeshulman** [comment]
Also, a question to someone else: is Travis just permanently useless now?  Can we fix it somehow so that it actually tells us whether a PR compiles or not, regardless of whatever other dpdgraph nonsense is broken?

**Comment by abooij** [comment]
(I forgot to add that I learned of this presentation of the naturals from Martín Escardó and Cory Knapp.)

@mikeshulman: Even if we could use univalence everywhere, this is not desirable. You don't want to compute `x+y` by first computing the unary representation of `x` and `y`, doing the unary addition, and then converting back to binary. Doing it in binary directly is faster. Similarly for e.g. deciding equalities.

I'm not sure how to characterize mathematically which things are computationally relevant. As a first approximation: everything that, when fully evaluated at closed terms, does _not_ result in a reflexivity path. Addition of binary naturals gives a new binary natural, which I might wish to print on the screen. So that's computationally relevant to me. Comparing two binary naturals might give < or = or >, so that is computationally relevant to me: there are different possible outcomes (although for fixed closed terms there is only one). But, for example, I won't print the path inhabiting 1+2=2+1 on the screen, because it is reflexivity.

But I'm not sure this answers your question.

**Comment by mikeshulman** [comment]
Good point about univalence!  What about the other direction; would we want to define operations on unary naturals in terms of binary ones?

As a second approximation to computational irrelevance, instead of just "reflexivity" what about saying that there is only one canonical form for closed terms?

**Comment by abooij** [comment]
Strictly speaking, one might not always want to go in the other direction either: for example, the successor operation is O(1) for unary, but O(log n) for binary. But I suppose that's not the worst of complexities :)

Your second approximation explains my choices in this PR, with the clarification that I only consider closed terms of non-function type. For example, inequalities like `ineq_bzero_double1 : bzero <> double1 n` are not relevant to me, even if for different closed terms `n` they give different terms, since we won't be able to further evaluate them to a non-function type.

**Comment by mikeshulman** [comment]
I'm confused -- are you saying that we should evaluate function terms fully on closed terms before comparing them, i.e. we could have two different function terms that would evaluate to the same thing on all closed terms?  In particular that would mean that no negation is ever computationally relevant --- which seems right --- since we can't ever evaluate it fully as there are no closed terms of type `Empty` to get out.

**Comment by abooij** [comment]
That sounds correct. Let me phrase my thoughts another way, to make sure.

I consider a construction `A` computationally relevant if the following situation is possible: after fully evaluating the proof of `A` at closed terms to obtain a term not of function type, it is possible to get different terms (canonical forms).

So negations are never computationally relevant, because we would have to evaluate to get a term of type **0**, which (hopefully) doesn't exist. And the equalities in the semiring axioms aren't computationally relevant, because they always result in the reflexivity path. But addition is relevant, because we may get `bzero` or `double1 bzero` or... And deciding paths is relevant, because we may get `inl idpath` or `inr (\ x -> ...)`. Ditto for the proof of trichotomy.

This definition isn't completely satisfactory either: what to think of proofs of product types? If both of the factors are negations, such as `forall n, (n <> n+1) x (n <> n+2)`, then my definition may still consider them computationally relevant: we can evaluate the term to obtain a non-function type `(n <> n+1) x (n <> n+2)` for some closed term `n`, with different canonical forms for different choices of `n`. However, both projections are computationally irrelevant, as they are negations. Or, in a different scenario, such as `A x (~ A)`, the second factor makes the first factor irrelevant: if `~A` then we can't have *any* terms of type `A`, so in particular we can't have two different ones. So what is the correct definition in general?

Luckily the latter scenarios don't arise in this PR.

**Comment by mikeshulman** [comment]
It feels like we want to be defining some sort of "syntactic extensional equality" by induction on types, so that it could descend into products as well as evaluating functions.

**Comment by spitters** [comment]
@mikeshulman About Travis, I understand the graph issue is now solved, so things should work again if we bump to the latest Coq. We should probably also do a new opam release them, but I was waiting for someone to confirm this.

**Comment by mikeshulman** [comment]
@spitters That's good to hear.  Can someone bump Coq?  Can I do that easily?

**Comment by spitters** [comment]
I think this was the last time it was done:
https://github.com/HoTT/HoTT/commit/5b6d2caeeb605e87c5b52193e091a0e497751663

**Comment by mikeshulman** [comment]
So I guess what I need to do is check out the "latest Coq" in the `coq-HoTT` subdirectory, then add that submodule to the commit.  But what does "latest" mean?  Which branch or tag?  Sorry, I've forgotten what our policy is here...

**Comment by spitters** [comment]
I think this is the latest version:
https://github.com/coq/coq/tree/V8.7.2
We should also update .travis.yml to V8.7.2 
(I also forgot the precise process for updating)

**Comment by spitters** [comment]
@mikeshulman I think we can pull this PR, can't we?

**Comment by mikeshulman** [comment]
Well, I haven't had a chance to actually look at the code yet, which I feel obligated to do before approving it.  (-:

**Pull request merged**
