### PR TITLE
put surreal cut notation in a module to avoid clobbering nested sigma-types

### PR DESCRIPTION
**Pull request by mikeshulman**

### CODE REVIEW

**Comment by JasonGross** [comment]
Have you checked that this fixes it?  I don't think it does, because `Reserved Notation` doesn't respect module boundaries.

**Comment by mikeshulman** [comment]
Kristina's example

```coq
Require Import HoTT.
Check ({ l : Unit & { n : Unit & Unit }}).
```

now works for me.  I added it to `Tests.v` so Travis will check it too.

**Comment by JasonGross** [comment]
While you're at it, do you want to `Bind Scope surreal_scope with No` right after you define `No`?

**Comment by JasonGross** [comment]
I'm confused.  Either it should be enough to put it in `surreal_scope` (and you shouldn't need to put it in a module), or putting it in a module shouldn't be enough to fix things...

**Comment by JasonGross** [comment]
LGTM, though I'd like to know why this works.

**Comment by mikeshulman** [comment]
Let me know if you figure it out.

**Comment by JasonGross** [comment]
Also, are you planning on a `Bind Scope`?

**Comment by mikeshulman** [comment]
Sure, I'll do it later tonight.

**Comment by mikeshulman** [comment]
scope bound.

**Comment by mikeshulman** [comment]
bump

**Comment by JasonGross** [comment]
We are just waiting for APOE?  (And I may or may not eventually investigate why this fixes things?)

**Comment by mikeshulman** [comment]
I think so.

**Pull request merged**
