### PR TITLE
[Overture] Get inversion working

### PR DESCRIPTION
**Pull request by artagnon**
The series of Register commands breaks build at the moment.

### CODE REVIEW

**Comment by Alizter** [comment]
I wouldn't replace the identity variables with the eq ones. That was a mistake in my post which I have since edited.

**Comment by Alizter** [comment]
What's `core.id.*`? I am only aware of `core.eq.*` and `core.identity.*`.

**Comment by Alizter** [comment]
The current error stems from the fact that registering `core.eq.type` changes the behaviour of rewrite.

**Comment by artagnon** [comment]
> What's core.id.*? I am only aware of core.eq.* and core.identity.*.

My bad. I think I misunderstood your comment on another thread.

**Comment by mikeshulman** [comment]
What's the status of this?  (And actually, what's the goal?)

**Comment by Alizter** [comment]
@mikeshulman The `inversion` tactic can prove inequalities between differing constructors of inductive types. On the coq end things are being changed (such as the registering of the empty type etc.) to allow us to use it.

For now however, it doesn't seem like this PR actually does what it says, so I am in favour of closing it until things change upstream.

**Pull request closed without merging**
