### PR TITLE
Lex modalities and the fracture theorem

### PR DESCRIPTION
**Pull request by mikeshulman**
Long-promised.  (-:  Some notes:

1. Also includes some general theory about pullbacks, in `Pullback.v`, and a notation `f^* g` for the pullback of `g` along `f`.
2. At first I tried making lex-ness a module type to be assumed on top of a modality module-type, as for accessibility.  But then I realized that since lex-ness is a "universe-local property" (unlike accessibility!) we can just make it a typeclass and allow ordinary universe polymorphism to kick in.
3. Given this, I was strongly tempted _not_ to include separate files `Lex` and `Topological`, putting the relevant theory into `Modality` or `Accessible` depending on whether it needs accessibility.  (This would even be possible for `Fracture`.)  This would have the advantage of avoiding the proliferation of `_Theory` modules and (presumably) solving the multiple-inheritance problem described in the comments in `Lex.v`.  I have so far resisted the temptation, but we'll see how annoyed I get in the future with the current setup.  (Would using `Include` instead of `Export`, if we trusted it to be anomaly-free, also solve these problems?)

### CODE REVIEW

**Comment by mikeshulman** [comment]
Rebased again.  (Among other things, I've been apparently using the notation `^*` for both pullbacks of maps and inversion of pointed homotopies.  Now I've put them in separate scopes, at least.)

**Comment by JasonGross** [comment]
Travis is unhappy.  What's the error message? (My phone's browser doesn't handle travis logs on low quality wifi.)

**Comment by mikeshulman** [comment]
I can't find an error message; it just ends on line 10000 while printing out `./theories/Pullback.timing`.

**Comment by mikeshulman** [comment]
I found some references on the internet to travis cutting off all logs after 10000 lines.  Can we change our build scripts to spew less so that we can see the actual error?

**Comment by JasonGross** [comment]
It cuts off after line 10000.  You click the "download log" button towards the top to get the full log.

**Comment by mikeshulman** [comment]
Looks like"trouble in init_rank" again.

**Comment by JasonGross** [comment]
Ugggghhh, `dot` is looping again.

**Comment by mikeshulman** [comment]
It would sure be nice if Travis would add a comment at the end saying "this build log has been truncated after 10000 lines; click Download Log at the top to obtain the complete log".

**Comment by JasonGross** [comment]
I'm sure they have a bug tracker / feature request form somewhere.

**Comment by mikeshulman** [comment]
This PR is coming up on 2 months old; it would be really nice to get it merged.

**Comment by JasonGross** [comment]
I will hopefully have a chance to look at `dot` again in the next week or two.

**Comment by mikeshulman** [comment]
Rebased again (`mapinO_pr1` was duplicated between this PR and a recent one).

**Comment by JasonGross** [comment]
Oh, hey, travis seems happy.  Do we need ASPOE, or has this been sitting around long enough without objections that we should just merge it?

**Comment by andrejbauer** [comment]
If I squint a little, I can be a second pair.

**Comment by spitters** [comment]
I am still motivated to actually read it, but I don't think that needs to
block merging.
Please go ahead and I'll send patches in necessary. Sorry, that this toke
so long.

**Comment by mikeshulman** [comment]
Thanks!

**Pull request merged**
