### PR TITLE
Add a reversed version of [rapply]

### PR DESCRIPTION
**Pull request by JasonGross**
This is necessary for getting #691 to work.

### CODE REVIEW

**Comment by mikeshulman** [comment]
LGTM

**Comment by spitters** [comment]
Do we need both `rapply` and `rapply'` ? I guess so.
The name is not very descriptive, but I don't know a better one.

Otherwise, LGTM

**Comment by JasonGross** [comment]
Alternative names: `rev_rapply`, `rapply_rev`.  The issue is that when you `rapply` a lemma ending in an equivalence, you need to decide whether you want to apply the function, or the equivalence.  If you make the wrong choice, you can make typeclass resolution loop.

**Comment by spitters** [comment]
I don't think the other names are any better they suggest applying A <- B

Feel free to merge.

**Comment by mikeshulman** [comment]
>  The issue is that when you rapply a lemma ending in an equivalence, you need to decide whether you want to apply the function, or the equivalence. If you make the wrong choice, you can make typeclass resolution loop.

Maybe a comment about that in the source code or the style file would be useful.

**Comment by JasonGross** [comment]
Added some more documentation, and `erapply'`.  Does it still look good to both of you?

**Comment by spitters** [comment]
LGTM

**Pull request merged**
