### PR TITLE
Update submodule to Coq V8.11.0

### PR DESCRIPTION
**Pull request by Alizter**
Once this is merged, I will make a release. See #1291

### CODE REVIEW

**Comment by Alizter** [comment]
@JasonGross What does this mean:
```
make -f Make_coq dpdgraph.vo
make[2]: Entering directory '/home/runner/work/HoTT/HoTT/etc/coq-dpdgraph'
CAMLOPT -c  searchdepend.ml
File "searchdepend.mlg", line 37, characters 11-35:
Warning 3: deprecated: ConstRef
Use Names.GlobRef.ConstRef
File "searchdepend.mlg", line 40, characters 11-36:
Warning 3: deprecated: IndRef
Use Names.GlobRef.IndRef
File "searchdepend.mlg", line 43, characters 11-45:
Warning 3: deprecated: ConstructRef
Use Names.GlobRef.ConstructRef
File "searchdepend.mlg", line 69, characters 50-52:
Error: This expression has type Opaqueproof.opaque Declarations.constant_body
       but an expression was expected of type Opaqueproof.indirect_accessor
make[2]: *** [searchdepend.cmx] Error 2
Make_coq:625: recipe for target 'searchdepend.cmx' failed
make[2]: Leaving directory '/home/runner/work/HoTT/HoTT/etc/coq-dpdgraph'
Makefile:71: recipe for target 'dpdgraph.vo' failed
make[1]: Leaving directory '/home/runner/work/HoTT/HoTT/etc/coq-dpdgraph'
Makefile:1035: recipe for target 'etc/coq-dpdgraph/coqthmdep' failed
make[1]: *** [dpdgraph.vo] Error 2
make: *** [etc/coq-dpdgraph/coqthmdep] Error 2
$ exit 2
$ exit 2
##[error]Process completed with exit code 2.
```

**Comment by JasonGross** [comment]
It means you need to update the coq-dpdgraph submodule to a version compatible with 8.11 (hopefully they have such a branch)

**Comment by Alizter** [comment]
While I'm at it, should I also update coq-scripts also? @JasonGross

**Comment by Alizter** [comment]
@JasonGross That might be a good idea. How might we go about doing that?

**Comment by JasonGross** [comment]
Two options:
1. Take the line that says something like FORCE_COQ_VERSION=master, and make a couple copies of that line in the matrix, replacing master with things like V8.11.0, V8.10.2, etc
2. Take the line that talks about the master-daily package, make a few copies of that line, and replace the package variables by the ones corresponding to other versions of Coq as in https://github.com/mit-plv/fiat-crypto/blob/master/.github/workflows/coq.yml

**Comment by JasonGross** [comment]
Note that the second option will take a little bit less time because it will install Coq rather than building it

**Pull request merged**
