### PR TITLE
update to coq 8.15

### PR DESCRIPTION
**Pull request by Alizter**
TODO:
 - [x] Wait for docker images to update to 8.15
 - [x] Wait for coq 8.15 to be released (currently 8.15+rc1 is out)

### CODE REVIEW

**Comment by JasonGross** [comment]
Do we also need to tag a commit for 8.14?

**Comment by Alizter** [comment]
@JasonGross There is already an 8.14 tag

**Comment by Alizter** [comment]
This is now good to go.

**Comment by Alizter** [comment]
cc @mikeshulman

**Review by mikeshulman — APPROVED** [review]

**Pull request merged**
