### PR TITLE
[Exercise 2.12] Solve using primitives in Pullback.v

### PR DESCRIPTION
**Pull request by artagnon**
This is a work-in-progress, and I wonder if this is the most
straightforward definition to supply proof for.

### CODE REVIEW

**Comment by Alizter** [comment]
No, we don't have this in the main library. I did prove it a few times before, but I never managed to merge those branches.

**Comment by Alizter** [comment]
This is the key thing to use when proving the 2-pullbacks lemma. Egbert mentioned this proof to me.

**Comment by Alizter** [comment]
#1370

**Comment by Alizter** [comment]
@artagnon We have the pasting lemma for pullbacks in Pullback.v now.

**Comment by artagnon** [comment]
On second thought, I think `ispullback_pasting_outer` is proving something subtly different from the problem statement.

**Comment by mikeshulman** [comment]
Right; that's what I was saying at #1331.  `ispullback_pasting_outer` *looks* like the statement of exercise 2.12, but is different because the meaning of "is a pullback square" defined in exercise 2.11 is different from `IsPullback`.

**Comment by mikeshulman** [comment]
Let's not leave this PR lying around open.

**Pull request closed without merging**
