### PR TITLE
adapt to coq/coq#15220

### PR DESCRIPTION
**Pull request by gares**
To be merge when https://github.com/coq/coq/pull/15220 is.

### CODE REVIEW

**Comment by JasonGross** [comment]
If this is backwards-incompatible, we should make sure that we tag a version for 8.15 and bump compatibility requirements before merging this.

**Comment by gares** [comment]
If you already test the version of Coq somewhere, I can make it so that this line is patched back on < 8.16

**Comment by Alizter** [comment]
@gares Since core plugins have understandable legacy names can we close this?

**Comment by SkySkimmer** [comment]
Feel free to merge if you want

**Comment by Alizter** [comment]
Also it's not a difficult PR to resurrect in the future so I am closing for now.

**Pull request closed without merging**
