### PR TITLE
Adding TOC to STYLE

### PR DESCRIPTION
**Pull request by spitters**

### CODE REVIEW

**Comment by JasonGross** [comment]
LGTM

**Comment by mikeshulman** [comment]
Could Travis auto-update this for us when the style file is changed?

**Comment by JasonGross** [comment]
Probably, but it's bad practice to mix autogenerated files with manually generated files.  Would it be sufficient to have travis error and print out a replacement TOC for PRs that update the file?

**Comment by mikeshulman** [comment]
What is bad about it in this instance?  We could add a comment to the markdown saying that the toc is autogenerated so that people don't try to edit it by hand.

**Comment by mikeshulman** [comment]
(Ideally, the autogenerated toc could be in another file that is included, but does markdown have include capabilities?)

**Comment by JasonGross** [comment]
You want it updated a la the erratum of the HoTT book?

**Comment by spitters** [comment]
The first line already states that it is generated.
This solution was suggested on stackexchange, but I am open to better ones.

**Table of Contents** *generated with [DocToc](
http://doctoc.herokuapp.com/)*

**Comment by mikeshulman** [comment]
Yes, like the errata.  If we do that, I would make the comment say more specifically that the toc will be auto-updated on every commit, rather than merely that it *was* autogenerated at one point.

**Pull request merged**
