### PR TITLE
Remove Bracketing Last Introduction Pattern, close #993

### LINKED ISSUE #993: Option Bracketing Last Introduction Pattern is deprecated
```
File "./theories/Basics/Overture.v", line 8, characters 0-50:
Warning: Option Bracketing Last Introduction Pattern is deprecated
[deprecated-option,deprecated]
```

as found out in #992 this is essential for Sum.v and a few other files to compile. What is the reason for this to still be used and what should we do about it?

### PR DESCRIPTION
**Pull request by mikeshulman**
I don't know if anyone is listening, but I think this is an argument against relying on fancy tactic stuff like this.  Not only does it make the code harder to step through and understand, but it renders it fragile to changes to the details of tactics, and when that happens it is hard to figure out how to fix it because it's hard to step through and understand.

### CODE REVIEW

**Comment by Alizter** [comment]
I agree there is a problem with the use of `intro []`. I wonder if it might be worth going through the library and finding "poorly written" code. Then people would know what to fix. Ones I have found which are difficult to read are the old stuff like Fibrations.v, the colimits library, Modalities/Topological.v etc.

**Comment by mikeshulman** [comment]
I don't have a problem with ordinary `intro []` which means to introduce something and immediately destruct it.  I do agree that Fibrations and colimits are hard to read, if anyone wants to clean them up that would be great.  I don't have a problem with Topological myself (unsurprisingly, since I wrote it), but if you have suggestions to improve it somehow that's great too.

**Comment by Alizter** [comment]
Can we resolve and merge this?

**Comment by spitters** [comment]
"This branch has conflicts that must be resolved"

**Comment by mikeshulman** [comment]
Rebased against master.  (Some of the changes overlapped with #998.)

**Pull request merged**
