### PR TITLE
WIP: [coq] Adapt to coq/coq#11948

### PR DESCRIPTION
**Pull request by proux01**
don't merge

### CODE REVIEW

**Comment by JasonGross** [comment]
Note that this will also need to update the submodule and the docs, as it causes us to lose compatibility with 8.11

**Comment by mikeshulman** [comment]
You can make it a "draft pull request" to prevent anyone from merging it.

**Comment by proux01** [comment]
> Note that this will also need to update the submodule and the docs, as it causes us to lose compatibility with 8.11

Sorry, will have a look

> You can make it a "draft pull request" to prevent anyone from merging it.

That seems only possible when creating the PR, will try not to forgot next time.

**Comment by proux01** [comment]
> Note that this will also need to update the submodule and the docs, as it causes us to lose compatibility with 8.11

So here is a solution that remains compatible with 8.11.

With the upstream PR, it will print a deprecation warning and parsing of nats in hexadecimal will not be available (but could be added later). I hope this provides a smoother transition path.

**Comment by Alizter** [comment]
LGTM

**Comment by JasonGross** [comment]
I have converted this to a draft PR, please mark as ready for review when it's ready.

**Comment by proux01** [comment]
@JasonGross well, the upstream PR may be waiting for your potential opinion https://github.com/coq/coq/pull/11948#pullrequestreview-394090216 ;) (seventh commit "Add hexadecimal numerals" is extending numeral notations)

**Comment by JasonGross** [comment]
Ah, I somehow missed that review request (and have recently tweaked my filters to not miss such emails again).  I'll aim to look at it today it today or in the near future

**Comment by JasonGross** [comment]
It is standard to merge backwards-compatible changes before the corresponding PR gets merged; given that, should we be merging this soon?

**Comment by proux01** [comment]
I would say yes, as far as I'm concerned.

**Comment by JasonGross** [comment]
Can you rebase this on master, so we get a fresh run of the CI? And then let's merge.

**Pull request merged**
