### PR TITLE
rename colimit functoriality results for consistency

### PR DESCRIPTION
**Pull request by mikeshulman**

### CODE REVIEW

**Comment by Alizter** [comment]
Limit also needs to be changed since I was following colimit.

**Comment by mikeshulman** [comment]
Thanks, done.

**Comment by spitters** [comment]
LGTM. I've restarted Travis. Please feel free to merge when travis is happy.

**Comment by Alizter** [comment]
At some point I changed HoTT.v to look for HoTT.Pullback rather than Pullback which has caused this build to fail now. We need to change this to HoTT.Limits.Pullback. I didn't notice this because travis wasn't rerun on the latest version in #1094.

**Comment by Alizter** [comment]
@mikeshulman I've sent you a PR fixing HoTT.v

**Comment by Alizter** [comment]
Travis is happy.

**Pull request merged**
