### PR TITLE
Proof of [IsHSet nat] added to Nat.v

### PR DESCRIPTION
**Pull request by marcbezem**
Proved by the encode/decode argument from Section 2.13

### CODE REVIEW

**Comment by marcbezem** [comment]
I see only now that there is already a hset_nat  in theories/Spaces/Nat.v. I have several questions now:
- Should I just close the pull request?
- Should the name conflict not be detected? Or maybe there is no conflict?
- How to avoid such duplicates in the future? It seems impossible to overlook the whole library.
I found it by coincidence, reading issue #784. Then a "grep -r hset_nat ." found it.
- BTW, "grep -r hprop_Empty ." succeeds, "grep -r hprop_Unit ." fails.

Thanks in advance (doing the proof was instructive anyway).

**Comment by andrejbauer** [comment]
I think this pull request could be closed, but not before we discuss how we got to have both `types/Nat.v` and `Spaces/Nat.v`. Any idea?

**Comment by mikeshulman** [comment]
Probably first we had `types/Nat.v` before `Spaces/` existed, and then once `Spaces/` was created I started putting stuff in `Spaces/Nat.v` because I thought it was a better fit (since `nat` is a particular type rather than a general type former), but never got around to moving everything that was already in `types/Nat.v`.  Unless there is some dependency reason that some facts about nat need to be in `types/`?

**Comment by marcbezem** [comment]
I would like to have one file Nat.v, but have no strong opinion whether it should be under Types or Spaces. Mike's argument about type formers would also apply to Empty, Unit and Bool, wouldn't it? Another view that could be defended is that they are all, like nat, nullary type formers.

For discovering duplicates, it would be nice to have some function searching the library. In hoqide,
if one selects "nat" in either Nat.v, and then clicks "Queries/Search" one gets dependent_choice, nat_rec, nat_rect, S and 0, with all there types. It seems to search Coq.Init.Datatypes.nat. But I'm aware that "Tell me all you know about nat" will return quite a lot. However, the Proviola-generated index *has* an entry "hset_nat [in HoTT.Spaces.Nat]", so in principle I could have avoided the duplication.

**Comment by mikeshulman** [comment]
Right, nat is of course a nullary type former.  But that argument could also be applied to most things in `Spaces/`, so we have to draw the line somewhere.  For Empty and Unit, at least, I think there are dependency arguments: `Types/` is lower down the dependency ladder, and Empty and Unit are used in lots of other places in the library.  The situation with Bool is admittedly less clear; I could probably see an argument for moving Bool into `Spaces/`.

**Comment by marcbezem** [comment]
What exactly does "Spaces" express? Empty and Unit are hprop's, Bool is not. That could be an argument to move Bool and nat to Spaces. Browsing Spaces, I already found a Bool.v there:

 HoTT/theories/Spaces/BAut/Bool.v

Again, I would prefer one file Bool.v as a plausible place to look for results on Bool.

**Comment by mikeshulman** [comment]
Baut/bool is not about bool, it's about baut(bool).

Spaces is about 'particular spaces' rather than 'type formers'. As we've
seen this is not a totally clear boundary, but I think of it as types is
part of the foundations whereas spaces is the mathematics we do in that
foundations.

**Comment by marcbezem** [comment]
I think the issue has been sufficiently discussed so that this pull request can now be closed.

**Comment by mikeshulman** [comment]
Another pull request unifying the two nat.v's would be welcome.

**Comment by marcbezem** [comment]
Sure, I can do that. It may even be the case that Types/nat.v duplicates stuff in the Coq-library, and is actually obsolete. Adding hprop_Unit to Unit.v is also on my list. (May take some time, very busy right now.)

**Comment by mikeshulman** [comment]
We didn't copy very much from the Coq library into the HoTT library, but you can look to see.  I think hprop_Unit should be inferrable automatically from contr_Unit and trunc_succ.

**Comment by marcbezem** [comment]
It is good to discuss this before I do something. Here are two examples:

Types/Nat.v has Definition nat_plus_comm (n m : nat) : n + m = m + n.
https://coq.inria.fr/library/Coq.Arith.Plus.html has Lemma plus_comm : forall n m, n + m = m + n.

Both https://coq.inria.fr/library/Coq.Arith.Factorial.html and Types/Nat.v have
Fixpoint factorial (n : nat) : nat
:= match n with
| 0 => 1
| S n => S n * factorial n
end.

There might be subtle differences (Qed vs Defined, not here).
I have not yet tested/changed anything. 
We should first make a decision on policy. This could be: reuse as much of the Coq library as is possible/convenient. If so, Types/Nat.v becomes obsolete, as far as I can see.

**Comment by andrejbauer** [comment]
This issue is closed. Let's move the discussion to a separate issue, see #790

**Pull request closed without merging**
