### PR TITLE
Rip out auto{conf,make} in favor of `coq_makefile`

### LINKED ISSUE #1299: Fix dependency graph generation
Because there's [a separate dependency graph for every constant in the library](http://hott.github.io/HoTT/file-dep-graphs/).  It's currently broken, though, and we should fix that.

_Originally posted by @JasonGross in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjM2MTE1NDAyOnYy/pull_request_review_threads/discussion_

### LINKED ISSUE #1430: Makefile uses nonexisting coqdep option -nois
In https://github.com/HoTT/HoTT/blob/8e83dd76fdb1a75036f99072bb648d5301e22ddc/Makefile.am#L231 and 3 other locations, the makefile invokes `coqdep` with `-nois`. AFAIK no coqdep version since 8.4.6 supported this option. You may want to limit coqdep invocations to existing options.

### LINKED ISSUE #1457: Use coq_makefile in makefile
We should switch to using the standard coq_makefile tool for building the library. This will make it easier to switch to a modern build system like dune in the future. And makes our library more homogeneous amongst other coq projects.

This already can be done, and is how the coq-platform release for HoTT is built.

### LINKED ISSUE #1458: Remove hoq scripts
Once we do #1457 we can completely remove our hoq scripts and switch to using regular coq.

This will mean we no longer have to maintain custom scripts. Our _CoqProject already allows PG and coqide to understand the HoTT library.

### PR DESCRIPTION
**Pull request by JasonGross**
I haven't really tested this much, but that's what the CI is for.   We should inspect the CI output to make sure I didn't break anything.

@andrejbauer I think last time I tried this (https://github.com/HoTT/HoTT/pull/180) you objected, so I'm tagging you in case your objections still hold.

I've mostly just transported things from `Makefile.am` to `Makefile.coq.local`.  I'm happy to answer any questions about what's going on in this PR.

Closes #1457
Closes #1458
Closes #1430
Closes #1299 (I think and hope; we should check this after the PR is merged and re-open if the dep graphs are not fixed, with the following exceptions that locally seem to not build (perhaps because they have no locally defined constants?): HoTT.Utf8, HoTT.Tactics.Nameless, HoTT.Tactics.BinderApply, HoTT.Spaces.Finite.Tactics, HoTT.Misc, HoTT.HoTT, HoTT.Basics.Utf8, HoTT.Basics.Notations)

### CODE REVIEW

**Comment by Alizter** [comment]
Wow good job! There is still an error in dpdgraph for some reason? Though I am unsure what is causing it.

**Comment by JasonGross** [comment]
dpdgraph job was failing because the way that dpdgraph generation worked changed at some point and we were still using an old version.  I've fixed it.

**Comment by JasonGross** [comment]
Incidentally, I think this will fix the file dependency graph generation

**Comment by JasonGross** [comment]
(The issue was, roughly, that we were missing `Require Import dpdgraph.dpdgraph.`)

**Comment by JasonGross** [comment]
Uh, GH Actions seems to be ignoring this PR now? :-(  I'm going to try closing and reopening it.

**Pull request closed without merging**
