### PR TITLE
changed implicit hints to reference core

### PR DESCRIPTION
**Pull request by Alizter**
As talked about in #991.

However now we cannot build. First problem is in Sum.v and is not the last.

### CODE REVIEW

**Comment by JasonGross** [comment]
That seems suspicious.  If you remove all the changes and just stick `Hint Resolve Set : core.` at the top of `Overture.v`, does that break everything as well?  (Current hypothesis: the first `Hint Resolve` creates the hint database in a way that breaks things.)

**Comment by Alizter** [comment]
@JasonGross `Set cannot be used as a hint.`

**Comment by JasonGross** [comment]
Er, just pick anything that exists.  Maybe, `Inductive foo := bar. Hint Resolve bar : core.`

**Comment by Alizter** [comment]
So I was getting:

```
File "./theories/Basics/Overture.v", line 8, characters 0-50:
Warning: Option Bracketing Last Introduction Pattern is deprecated
[deprecated-option,deprecated]
```

So I removed the culprit without thinking much. Apparently we need it to make Sum.v work but this is another issue.

This has nothing to do with hint databases so I think we can merge it. I will check the travis log just to see if we missed any however.

**Pull request merged**
