### PR TITLE
[coq] Adapt to coq/coq#12218

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by proux01** [comment]
Upstream PR merged, please merge.

**Comment by JasonGross** [comment]
Hm, this will also need to bump the submodule, since, given the change in the name of the ml plugin, we can't be compatible with both 8.12 and master at the same time.

**Comment by Alizter** [comment]
Why can't we be compatible at the same time?

**Comment by JasonGross** [comment]
The ML module numeral_notation_plugin exists only in 8.12 and must be declared to use numeral notations in 8.12.  It does not exist in current master anymore, so I don't see a way to make these co-exist.

**Comment by Alizter** [comment]
Why do we need to declare it at all?

**Comment by Zimmi48** [comment]
> Why do we need to declare it at all?

That's the usual "HoTT duplicates part of Coq's prelude" issue. Are we close to solving this now?

**Comment by Alizter** [comment]
We were close, but I was waiting for things on the dune happen to progress.

It doesn't seem like this particular change is necessary. We shouldn't really need to add anymore prelude.

If people wish to use these new numeral notations, then we can think about supporting them, i.e. doing a release for the library that supports them.

**Comment by JasonGross** [comment]
This is not a new feature, but a change to an existing one.  We already use numeral notations for nat, trunc_index, and Z if we use it.  If we drop numeral notations, we'll have to hard-code notations for every single numeral we use.

**Comment by proux01** [comment]
> Hm, this will also need to bump the submodule

Here it is, hope I haven't done anything wrong.

**Comment by JasonGross** [comment]
The submodule commit was set to c55d7606b4d7b45418bcb091f995551fbc0ef852, which does not seem to be on any branch; it should be set to afc828b3e207dd39c59d1501d570a88b2012fd2c (https://github.com/coq/coq/commit/afc828b3e207dd39c59d1501d570a88b2012fd2c)

**Comment by proux01** [comment]
Indeed, here it is.

**Comment by JasonGross** [comment]
I'm updating my Coq package at https://code.launchpad.net/~jgross-h/+recipe/coq-master-daily-coqide-no, and we should restart the CI once it completes.  I expect everything to pass, though, since the CI passed here on master.

**Review by JasonGross — APPROVED** [review]
LGTM once the CI passes

**Comment by SkySkimmer** [comment]
Does CI need to be restarted or what?

**Comment by Alizter** [comment]
I've bumped the coq-dpdgraph submodule. Hopefully this works.

**Pull request merged**
