### PR TITLE
Adapt to coq/coq#13842

### PR DESCRIPTION
**Pull request by proux01**
This should be backward compatible.

### CODE REVIEW

**Comment by proux01** [comment]
The CI failure seem unrelated

**Comment by ppedrot** [comment]
If this is backwards compatible, can we get this merged before the upstream PR? Thanks.

**Review by mikeshulman — APPROVED** [review]
Works for me.

**Comment by Alizter** [comment]
@proux01 Can you rebase so that the CI works a bit more. I fixed some issues in #1421

**Comment by proux01** [comment]
> @proux01 Can you rebase so that the CI works a bit more. I fixed some issues in #1421

@Alizter done but the result doesn't seem very convincing :(

**Comment by ppedrot** [comment]
IIUC HoTT CI is currently broken, so we can't be sure this PR is fine? Can't it be tested locally so that it can get merged? I'd like to merge the upstream PR soon but doing so would force you to merge this one right after anyways.

**Comment by proux01** [comment]
If you want to trust me: I compiled it on my machine and it was fine.

**Comment by mikeshulman** [comment]
I already checked it locally and approved it, and it's been 2 days, so i think we're good to merge.

**Comment by ppedrot** [comment]
Thanks!

**Pull request merged**
