### PR TITLE
[Exercise 2.11] Solved using equiv_compose

### PR DESCRIPTION
**Pull request by artagnon**
~~Again, I'm not sure if I've answered the question in its entirety.~~

I've modified the solution to use `IsPullback`, and it looks obviously correct this time around.

### CODE REVIEW

**Comment by mikeshulman** [comment]
`IsPullback` is the *statement* that a given commutative square is equivalent to "the" concretely defined pullback.  This is not the same as the definition of "pullback square" given in Ex. 2.11.

**Comment by Alizter** [comment]
I think exercise 2.11 is asking if the square obtained from the canonical pullback `pullback_commsq` satisfies `IsPullback` which should be evident.

**Comment by mikeshulman** [comment]
Exercise 2.11 is asking if `pullback_commsq` satisfies *a* definition of "being a pullback", but that definition is different from our `IsPullback`.

**Comment by artagnon** [comment]
I wasn't able to figure out how to use `pullback_commsq`, but the solution hopefully looks better now?

**Comment by mikeshulman** [comment]
No, you still aren't actually engaging with the definition of "pullback square" *as given in the exercise*.

**Comment by mikeshulman** [comment]
Let's not leave this PR lying around open.

**Pull request closed without merging**
