### PR TITLE
Make HoTT compile with 8.5beta3

### PR DESCRIPTION
**Pull request by JasonGross**
We probably don't want to merge this yet, given that 8.5beta3 incurs a 3x slowdown over 8.5beta2:
```
After    | File Name                                                 | Before   || Change
--------------------------------------------------------------------------------------------
9m17.26s | Total                                                     | 3m35.47s || +5m41.79s
--------------------------------------------------------------------------------------------
1m01.59s | categories/Category/Sigma/Univalent                       | 0m11.02s || +0m50.57s
0m45.68s | hit/FreeIntQuotient                                       | 0m01.93s || +0m43.75s
0m38.37s | Spaces/Finite                                             | 0m05.67s || +0m32.69s
0m40.97s | hit/V                                                     | 0m11.04s || +0m29.92s
0m35.95s | contrib/Freudenthal                                       | 0m06.62s || +0m29.33s
0m34.28s | Spaces/No                                                 | 0m05.20s || +0m29.08s
0m29.99s | categories/LaxComma/CoreLaws                              | 0m02.98s || +0m27.00s
0m23.35s | categories/Category/Paths                                 | 0m02.38s || +0m20.97s
0m13.54s | hit/Truncations                                           | 0m01.10s || +0m12.43s
0m20.43s | Spaces/BAut/Bool                                          | 0m11.50s || +0m08.92s
0m06.82s | categories/Functor/Composition/Functorial/Attributes      | 0m00.85s || +0m05.97s
0m06.84s | Spaces/BAut                                               | 0m02.41s || +0m04.42s
0m20.16s | categories/Adjoint/Pointwise                              | 0m24.01s || -0m03.85s
0m10.32s | Algebra/ooGroup                                           | 0m06.72s || +0m03.60s
0m08.80s | Modalities/Lex                                            | 0m05.38s || +0m03.42s
0m04.79s | contrib/HoTTBook                                          | 0m01.22s || +0m03.57s
0m03.68s | hit/quotient                                              | 0m00.55s || +0m03.12s
0m11.83s | Modalities/ReflectiveSubuniverse                          | 0m08.96s || +0m02.86s
0m07.41s | Pointed                                                   | 0m05.02s || +0m02.39s
0m03.71s | hit/Connectedness                                         | 0m01.39s || +0m02.32s
0m02.35s | categories/GroupoidCategory/Dual                          | 0m00.19s || +0m02.16s
0m06.83s | Idempotents                                               | 0m05.77s || +0m01.06s
0m05.40s | categories/Adjoint/Functorial/Laws                        | 0m04.37s || +0m01.03s
0m03.50s | Modalities/Modality                                       | 0m02.23s || +0m01.27s
0m02.83s | Algebra/Aut                                               | 0m01.22s || +0m01.61s
0m02.26s | hit/epi                                                   | 0m00.84s || +0m01.41s
0m02.24s | Spaces/BAut/Cantor                                        | 0m01.23s || +0m01.01s
0m02.11s | categories/Category/Morphisms                             | 0m00.98s || +0m01.12s
0m01.93s | categories/Grothendieck/ToSet/Morphisms                   | 0m00.89s || +0m01.04s
0m01.74s | DProp                                                     | 0m00.58s || +0m01.16s
0m01.68s | Constant                                                  | 0m00.42s || +0m01.26s
0m01.58s | categories/Functor/Paths                                  | 0m00.55s || +0m01.03s
```

### CODE REVIEW

**Comment by JasonGross** [comment]
Slowest things in the new version of `Finite.v`:
```
0.501 secs (0.5u,0.s) Chars 29432 - 29466 [refine~(quotient_ind_prop~R'~_...]
0.609 secs (0.608u,0.s) Chars 30476 - 30515 [apply~isembedding_isinj_hset;~...]
0.637 secs (0.636u,0.s) Chars 21024 - 21092 [refine~(fcard_equiv~(equiv_sum...]
0.748 secs (0.748u,0.s) Chars 16793 - 16811 [strip_truncations.]
1.141 secs (1.14u,0.s) Chars 29697 - 29742 [refine~(quotient_ind_prop~R''~...]
1.149 secs (1.147u,0.s) Chars 30298 - 30332 [refine~(quotient_ind_prop~R'~_...]
1.453 secs (1.447u,0.s) Chars 29753 - 29808 [revert~u;~refine~(quotient_ind...]
2.921 secs (2.919u,0.s) Chars 30562 - 30607 [refine~(quotient_ind_prop~R''~...]
3.782 secs (3.78u,0.s) Chars 30668 - 30713 [refine~(quotient_ind_prop~R''~...]
4.716 secs (4.716u,0.s) Chars 31136 - 31198 [revert~u;~refine~(quotient_ind...]
8.601 secs (8.6u,0.s) Chars 29183 - 29201 [strip_truncations.]
```
Slowest things with 8.5beta2:
```
0.09 secs (0.076u,0.015s) Chars 82 - 184 [Require~Import~Fibrations~Fact...]
0.093 secs (0.096u,0.s) Chars 27104 - 27159 [refine~(decidable_equiv~_~(hfi...]
0.097 secs (0.095u,0.s) Chars 19498 - 19554 [refine~(fcard_equiv~(sum_distr...]
0.108 secs (0.108u,0.s) Chars 20044 - 20151 [refine~~(finite_equiv'~_~(equi...]
0.113 secs (0.108u,0.003s) Chars 2859 - 2865 [simpl.]
0.122 secs (0.124u,0.s) Chars 22072 - 22122 [refine~(fcard_equiv~(equiv_fin...]
0.125 secs (0.128u,0.s) Chars 3286 - 3312 [destruct~k~as~[|~k];~simpl.]
0.187 secs (0.188u,0.s) Chars 32688 - 32731 [assert~(MapIn~-1~h)~by~(unfold...]
0.199 secs (0.199u,0.s) Chars 3685 - 3711 [destruct~k~as~[k|~];~simpl.]
0.2 secs (0.199u,0.s) Chars 21024 - 21092 [refine~(fcard_equiv~(equiv_sum...]
0.283 secs (0.283u,0.s) Chars 29183 - 29201 [strip_truncations.]
```

**Comment by ppedrot** [comment]
Is is still the case with the final 8.5 version? I sort of remember having fixed a performance bug of this kind between 8.5beta3 and 8.5rc1.

**Comment by JasonGross** [comment]
@ppedrot, I'm having trouble adapting the code to the changes in the universe minimization algorithm, but, at least for categories/Category/Sigma/Univalent, it's still much slower in the released version.  There's a failing typeclass search with the same trace in 8.5 beta 2 and 8.5 that takes 6 to 7 times longer in the released version.

**Comment by ppedrot** [comment]
Do you have minimal working state for Sigma.v I can fiddle with to trace performances?

**Comment by JasonGross** [comment]
@ppedrot, how minimal are you looking for?  Is 10957 lines small enough? ;)  Or I can give just point you at a branch and makefile target that'll build with 8.5beta2 and also 8.5 released?  The branch is https://github.com/JasonGross/HoTT/tree/xxx-bug-slow-typeclass, and you can run
```bash
./autogen.sh && COQBIN="/path/to/coq/bin/" ./configure && make clean && make TIMED=1 -kj theories/bug_csu_slow_tc_01.vo
```
You'll need to change `simple refine` to `refine` in `bug_csu_slow_tc_01.v` to get it to build with 8.5beta2, but everything other than that should build fine with both 8.5beta2 and 8.5.
On my machine, I get, with 8.5beta2:
```
HOQC theories/bug_csu_slow_tc_01
Finished transaction in 3.246 secs (3.248u,0.s) (successful)
Finished transaction in 0.533 secs (0.532u,0.s) (successful)
Finished transaction in 3.208 secs (3.208u,0.s) (successful)
Finished transaction in 1.268 secs (1.267u,0.s) (successful)
Finished transaction in 3.182 secs (3.184u,0.s) (successful)
Finished transaction in 0.528 secs (0.527u,0.s) (successful)
Finished transaction in 3.159 secs (3.16u,0.s) (successful)
Error: There are pending proofs
Command exited with non-zero status 1
theories/bug_csu_slow_tc_01 (user: 16.72 mem: 319720 ko)
make: *** [theories/bug_csu_slow_tc_01.vo] Error 1
```
with 8.5 released:
```
HOQC theories/bug_csu_slow_tc_01
Finished transaction in 4.71 secs (4.712u,0.s) (successful)
Finished transaction in 4.219 secs (4.22u,0.s) (successful)
Finished transaction in 4.632 secs (4.632u,0.s) (successful)
Finished transaction in 13.448 secs (13.444u,0.008s) (successful)
Finished transaction in 4.681 secs (4.68u,0.s) (successful)
Finished transaction in 4.22 secs (4.219u,0.s) (successful)
Finished transaction in 4.616 secs (4.612u,0.004s) (successful)
File "./theories/bug_csu_slow_tc_01.v", line 296, characters 4-26:
Timeout!
Command exited with non-zero status 1
theories/bug_csu_slow_tc_01 (user: 44.86 mem: 336200 ko)
make: *** [theories/bug_csu_slow_tc_01.vo] Error 1
```

**Comment by ppedrot** [comment]
Thanks, I'll have a look.

**Comment by JasonGross** [comment]
I now have [a branch compatible with 8.5rc1](https://github.com/JasonGross/HoTT/tree/8.5rc1), which has a negligable change in timing w.r.t. 8.5beta3.  I'm currently tracking down some bugs in 8.5 released which weren't present in 8.5rc1 (`refine` can generate ill-typed proof terms).  Also (@ppedrot, @mattam82), is the behavior of `rewrite` supposed to be different in 8.5 released vs 8.5rc1?  There's a place where I need `rewrite !foo` where `rewrite foo` is sufficient in 8.5rc1.

**Comment by mattam82** [comment]
Hmm, the rewrite change might be due to fixes in Keyed Unification. Do you have a small example demonstrating the change?

**Comment by JasonGross** [comment]
I'll set my bug minimizer on it, and should have a moderately small example in a day or two.  Thanks!

**Comment by JasonGross** [comment]
@mattam82, I'm minimizing (one of) the `rewrite` changes now, but the problem seems to be that `rewrite` prefers unfolding definitions over not unfolding definitions.  I start with
```coq
(p2 @ (p0 @ p1)) @ eissect (to O A) (g x) = r
```
I `rewrite concat_p_pp`, and then I get
```coq
(((p2 @ (p0 @ p1)) @
  (ap (O_rec idmap) (ap (to O A) (O_rec_beta idmap (g x))^) @
   ap (O_rec idmap)
     (O_indpaths (fun x : O A => to O A (O_rec idmap x)) idmap
        (fun x : A => ap (to O A) (O_rec_beta idmap x))
        (to O A (g x))))) @ O_rec_beta idmap (g x) = r)
```
in 8.5, rather than what I expect to get (and what I get in rc1),
```coq
p2 @ p0 @ p1 @ eissect (to O A) (g x) = r
```

**Comment by JasonGross** [comment]
@ppedrot, I uploaded a minimized version to [bug 4537](https://coq.inria.fr/bugs/show_bug.cgi?id=4537), and assigned the bug to you (let me know if the assignment is wrong).

**Comment by JasonGross** [comment]
@ppedrot, thanks for fixing 4537!  This fixes most of the issues (and makes `categories/Adjoint/Pointwise` significantly faster!), except a seemingly nonterminating rewrite.  There are still a few files that got a bit slower, primarily `hit/V.v` got about 40% slower:
The big changes from 8.5beta2 to 8.5-22a2cc are:
```
After    | File Name                           | Before   || Change   
----------------------------------------------------------------------
>2m08.39s| Algebra/ooGroup                     | 0m06.72s || +2m01.66s
0m05.84s | categories/Adjoint/Pointwise        | 0m24.01s || -0m18.17s
0m15.51s | hit/V                               | 0m11.04s || +0m04.47s
0m13.56s | categories/Category/Sigma/Univalent | 0m11.02s || +0m02.54s
0m07.67s | contrib/Freudenthal                 | 0m06.62s || +0m01.04s
0m04.29s | Modalities/Lex                      | 0m05.38s || -0m01.08s
```

**Comment by ppedrot** [comment]
It seems that hit/V passes most of its time in universe comparisons. I believe that using JH's patch on universes would make it really quicker.

**Pull request closed without merging**
