### PR TITLE
mention in INSTALL that you need to install zarith from opam

### PR DESCRIPTION
**Pull request by mikeshulman**
I had to do this before I could compile our currently pinned Coq.

### CODE REVIEW

**Comment by jdchristensen** [comment]
Yes, I had to do that a couple of months ago too.  I thought it was something messed up in my config.  BTW, I didn't install the gtk packages.  It's mentioned earlier on the page that these are for coqide, but maybe we should separate them out in the cut-and-paste part, with a repeat of that remark?

**Comment by jdchristensen** [comment]
The patch itself LGTM.

**Comment by mikeshulman** [comment]
Yeah, that makes sense.

**Comment by Alizter** [comment]
LGTM

**Comment by Alizter** [comment]
So the configure script from the main coq repo wasn't correctly raising the fact that zarith wasn't installed. https://github.com/coq/coq/issues/13041

Now that that has been fixed, we should update our configure script to also do this.

**Pull request merged**
