### PR TITLE
Make center of contr_basedequiv compute

### PR DESCRIPTION
**Pull request by jdchristensen**
For some reason, with the current proofs of `contr_basedequiv` and `contr_basedequiv'`, the following cause Coq to spin:

```
Compute (center {Y : Type & nat <~> Y}).
Compute (center {Y : Type & Y <~> nat}).
Compute (@center {Y : Type & nat <~> Y} (@contr_basedequiv nat)).
Compute (@center {Y : Type & Y <~> nat} (@contr_basedequiv' nat)).
```

So I replaced their proofs with proofs that give explicit centers.

### CODE REVIEW

**Comment by mikeshulman** [comment]
So why does `exists` work in the first case but not the second?  Apparently Coq is able to guess that `Equiv X Y` is the type family `Equiv X` applied to `Y`, but not that the type family `Equiv Y X` is the type family `fun Z => Equiv Z X` applied to `Y`.  Is that because the first doesn't need an abstraction?  It seems bizarre that the order of arguments matters like this.

**Comment by jdchristensen** [comment]
I have no idea why `exists` doesn't work in the second case.  There are several ways to make it work, but this way avoided writing out the type family.  One can also use `exists (exist (fun ...) X equiv_idmap)` (from memory), but that seems harder to read.

**Comment by jdchristensen** [comment]
Another asymmetry is that we don't have the other one-sided form of `equiv_induction`.  In this case, `equiv_induction'` worked easily, but we could also add something like `equiv_induction_sym`.

**Comment by mikeshulman** [comment]
I think it'd be nice to include a comment in the file saying something about why the proofs are different, or at least remarking on it -- or perhaps change the first proof to match the second.

I see that again you're using the `revert` trick here to enable Coq to guess the type family for `equiv_induction`.  Did you figure that out yourself?

I'd be in favor of an `equiv_induction_sym` (or perhaps `equiv_induction_opp` or `equiv_induction_inv` -- the latter is closer to our names for inverses of equivalences, so perhaps more suggestive of what it means).

**Comment by jdchristensen** [comment]
Ok, I added a comment explaining the problem with `exists`.  And I added `equiv_induction_inv`, which now makes the two new proofs more similar.  We could go further and define an `_inv` version of `path_ind`, or is it already somewhere?  I'm surprised it hasn't been needed.

**Comment by jdchristensen** [comment]
I'm not sure whether I figured out the `revert` trick myself or saw it somewhere.

**Comment by mikeshulman** [comment]
I think most of the time we only do path induction when both endpoints are free.

**Comment by Alizter** [comment]
I am not sure why trunc_equiv' needs to be opaque, but it does break some things when it is made transparent. I highlighted the issue in #1091. The first file which blows up is Spaces/Card.v

**Comment by jdchristensen** [comment]
I just thought of a way to simplify the three equiv_induction* proofs, and pushed an update.  Sorry to add this churn just when you were probably about to commit it.

**Comment by Alizter** [comment]
@jdchristensen No problem, are you OK with merging this now? I will wait till travis is happy.

**Comment by jdchristensen** [comment]
Yes, I'm happy now.  BTW, was your comment about trunc_equiv' meant for another issue?

**Comment by Alizter** [comment]
@jdchristensen No, I think it is the reason contr_basedequiv' was not computing before.

**Comment by jdchristensen** [comment]
Ah, I get it.  Thanks for explaining the issue.

**Pull request merged**
