### PR TITLE
Drop support for systems without autoconf

### PR DESCRIPTION
**Pull request by JasonGross**
Closes #868

See https://github.com/HoTT/HoTT/pull/851#issuecomment-305111736 and
surrounding comments.

While we're at it, also remove update_opam, since we no longer use a
custom version of Coq, and coq.hott no longer exists on opam.

### CODE REVIEW

**Comment by spitters** [comment]
OK when Travis is happy.

**Comment by andrejbauer** [comment]
I don't know about this. Autoconf was never supposed to be something that exists on the user side. It's a tool for developers to create portable installation scripts. This made sense before git existsed and people downloaded bundles of software that then installed itself.

How often does the configure script get changed nowadays? If not very often, we could perhaps include it in the repo?

**Comment by mikeshulman** [comment]
My instinct would be that anyone cloning the git repo should be considered a "developer".  We should provide other ways for "users" to install the package, such as opam or a tarball including `configure`.

**Comment by mikeshulman** [comment]
What's the status of this?

**Comment by Alizter** [comment]
I'm in favour of merging this once the conflicts have been resolved.

**Pull request closed without merging**
