### PR TITLE
Update to Coq V8.12

### PR DESCRIPTION
**Pull request by Alizter**
Coq 8.12 has been released. I've updated the Coq submodule and updated INSTALL.md.

This is a draft for now as there are a lot of new warnings we will have to resolve.

When I make the library on my machine I get the following warnings:

<details>
<summary> `make -j16 > /dev/null` </summary>
  
```
*** Warning: in file coq/theories/Init/Prelude.v, declared ML module numeral_notation_plugin has not been found!
*** Warning: in file coq/theories/Init/Notations.v, declared ML module ltac_plugin has not been found!
File "./coq/theories/Init/Peano.v", line 37, characters 0-30:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./coq/theories/Init/Peano.v", line 38, characters 0-38:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./coq/theories/Init/Prelude.v", line 19, characters 0-91:
Warning: Deprecated Numeral Notation for Decimal.uint, Decimal.int or
Decimal.decimal. Use Numeral.uint, Numeral.int or Numeral.numeral
respectively. [decimal-numeral-notation,deprecated]
File "./coq/theories/Init/Prelude.v", line 21, characters 0-85:
Warning: Deprecated Numeral Notation for Decimal.uint, Decimal.int or
Decimal.decimal. Use Numeral.uint, Numeral.int or Numeral.numeral
respectively. [decimal-numeral-notation,deprecated]
File "./coq/theories/Init/Prelude.v", line 25, characters 0-79:
Warning: Deprecated Numeral Notation for Decimal.uint, Decimal.int or
Decimal.decimal. Use Numeral.uint, Numeral.int or Numeral.numeral
respectively. [decimal-numeral-notation,deprecated]
File "./coq/theories/Init/Peano.v", line 96, characters 0-34:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./coq/theories/Init/Peano.v", line 97, characters 0-50:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./coq/theories/Init/Peano.v", line 136, characters 0-35:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Basics/Notations.v", line 46, characters 0-75:
Warning: The only parsing modifier has no effect in Reserved Notation.
[irrelevant-reserved-notation-only-parsing,parsing]
File "./theories/Basics/Notations.v", line 96, characters 0-74:
Warning: The only parsing modifier has no effect in Reserved Notation.
[irrelevant-reserved-notation-only-parsing,parsing]
File "./theories/Basics/Notations.v", line 102, characters 0-75:
Warning: The only parsing modifier has no effect in Reserved Notation.
[irrelevant-reserved-notation-only-parsing,parsing]
File "./theories/Basics/Utf8.v", line 3, characters 0-49:
Warning: The only parsing modifier has no effect in Reserved Notation.
[irrelevant-reserved-notation-only-parsing,parsing]
File "./theories/Basics/Overture.v", line 663, characters 0-46:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Basics/Overture.v", line 663, characters 0-46:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Basics/Overture.v", line 667, characters 0-28:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Category/Core.v", line 116, characters 0-79:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Category/Core.v", line 116, characters 0-79:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Category/Core.v", line 116, characters 0-79:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Functor/Core.v", line 63, characters 0-61:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Functor/Core.v", line 63, characters 0-61:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/NaturalTransformation/Core.v", line 67, characters 0-57:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Basics/Trunc.v", line 78, characters 0-102:
Warning: Deprecated Numeral Notation for Decimal.uint, Decimal.int or
Decimal.decimal. Use Numeral.uint, Numeral.int or Numeral.numeral
respectively. [decimal-numeral-notation,deprecated]
File "./theories/Spaces/Pos/Core.v", line 398, characters 0-69:
Warning: Deprecated Numeral Notation for Decimal.uint, Decimal.int or
Decimal.decimal. Use Numeral.uint, Numeral.int or Numeral.numeral
respectively. [decimal-numeral-notation,deprecated]
File "./theories/Spaces/Int/Core.v", line 88, characters 0-71:
Warning: Deprecated Numeral Notation for Decimal.uint, Decimal.int or
Decimal.decimal. Use Numeral.uint, Numeral.int or Numeral.numeral
respectively. [decimal-numeral-notation,deprecated]
File "./theories/Diagrams/Cone.v", line 30, characters 28-29:
Warning: Ignoring implicit binder declaration in unexpected position.
[unexpected-implicit-declaration,syntax]
File "./theories/Diagrams/Cone.v", line 30, characters 30-31:
Warning: Ignoring implicit binder declaration in unexpected position.
[unexpected-implicit-declaration,syntax]
File "./theories/Diagrams/Cocone.v", line 30, characters 28-29:
Warning: Ignoring implicit binder declaration in unexpected position.
[unexpected-implicit-declaration,syntax]
File "./theories/Diagrams/Cocone.v", line 30, characters 30-31:
Warning: Ignoring implicit binder declaration in unexpected position.
[unexpected-implicit-declaration,syntax]
File "./theories/Categories/Category/Morphisms.v", line 377, characters 0-131:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Category/Morphisms.v", line 377, characters 0-131:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Category/Morphisms.v", line 377, characters 0-131:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Category/Morphisms.v", line 377, characters 0-131:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Functor/Composition/Laws.v", line 45, characters 0-65:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Functor/Composition/Laws.v", line 45, characters 0-65:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Functor/Composition/Laws.v", line 68, characters 0-47:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/PseudonaturalTransformation/Core.v", line 232, characters 0-116:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/PseudonaturalTransformation/Core.v", line 232, characters 0-116:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Adjoint/Composition/IdentityLaws.v", line 55, characters 0-57:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Adjoint/Composition/IdentityLaws.v", line 55, characters 0-57:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Categories/Adjoint/Composition/AssociativityLaw.v", line 50, characters 0-39:
Warning: Declaring arbitrary terms as hints is fragile; it is recommended to
declare a toplevel constant instead [fragile-hint-constr,automation]
File "./theories/Modalities/Localization.v", line 288, characters 2-539:
Warning: Not a truly recursive fixpoint. [non-recursive,fixpoints]
File "./theories/Classes/implementations/binary_naturals.v", line 602, characters 2-159:
Warning: Not a truly recursive fixpoint. [non-recursive,fixpoints]
``` 
</details>

In summary:
 * `*** Warning: in file coq/theories/Init/Prelude.v, declared ML module numeral_notation_plugin has not been found!` This is #1134.
 * `Warning: Declaring arbitrary terms as hints is fragile; it is recommended to declare a toplevel constant instead [fragile-hint-constr,automation]`. This seems to be the most common warning. I am not too familiar with hints so I am not sure what the best practice here should be.
* `Warning: Deprecated Numeral Notation for Decimal.uint, Decimal.int or Decimal.decimal. Use Numeral.uint, Numeral.int or Numeral.numeral respectively. [decimal-numeral-notation,deprecated]`
* `Warning: The only parsing modifier has no effect in Reserved Notation. [irrelevant-reserved-notation-only-parsing,parsing]`
* `Warning: Ignoring implicit binder declaration in unexpected position. [unexpected-implicit-declaration,syntax]`
* `Warning: Not a truly recursive fixpoint. [non-recursive,fixpoints]`

I'll try and resolve the warnings I know how to.

### CODE REVIEW

**Comment by Alizter** [comment]
I've removed the final 3 warnings. In order to fix the Decimal warning we need to modify the coq prelude. Since I am currently working on minimizing the coq prelude that the library needs (i.e. eventually remove it completely) I will not bother with getting rid of that warning.

The only real warning left is the hint one.

**Comment by Alizter** [comment]
@JasonGross Do you know what is going wrong with dependency graphs here?

**Comment by Alizter** [comment]
I've suppressed the `fragile-hint-constr` warning since a solution will come in a later coq version coq/coq#12493. I've also suppressed the `decimal-numeral-notation` warning since it doesn't really make sense for us. In the future we will be getting rid of our version of the stdlib anyway, so we can remove this suppression then.

**Comment by Alizter** [comment]
Only the dependency graph is left and I have no idea how to fix that.

**Comment by spitters** [comment]
Thanks for the great work. Maybe we should consider again to just remove dpd-graph. It's too fragile.
@JasonGross ?

**Comment by JasonGross** [comment]
The way to fix the dpdgraph issue is to just bump the dpdgraph submodule to a version that's compatible with the version of Coq that we're using.  The tip of the coq-master branch should hopefully work, and if not, you can [file an issue](https://github.com/Karmaki/coq-dpdgraph/issues/new) asking them to make a release for 8.12

**Comment by JasonGross** [comment]
> I've also suppressed the `decimal-numeral-notation` warning since it doesn't really make sense for us. In the future we will be getting rid of our version of the stdlib anyway, so we can remove this suppression then

Alternatively, you can just do the renaming from `Decimal.*` to `Numeral.*`

**Comment by JasonGross** [comment]
Regarding the hint warnings, there are at least some instances of things like
```coq
Hint Immediate @left_identity @right_identity : category functor.
```
where you can remove the `@` (from `Hint Resolve` and `Hint Immediate` only, *not* from `Hint Rewrite`) without changing the meaning, and this will get rid of the warning.  Similarly, if there are any `Hint Resolve (@foo)` that should be changed to `Hint Resolve foo`.  This will probably get rid of a large fraction of the warnings.

**Comment by Alizter** [comment]
I sent a PR to coq-depgraph Karmaki/coq-dpdgraph#73. On my own machine it seems that pointing the submodule to this commit fixes the issue. I don't think it is good practice to point to a commit sitting in my branch however, so I will wait till that PR is merged before updating the submodule here.

**Comment by Alizter** [comment]
> Alternatively, you can just do the renaming from Decimal.* to Numeral.*
This will require renaming the file as well which seems more hassle than it is worth to get round this warning. I will keep it suppressed since this whole shadow of the stdlib is going to disappear soon anyway.

**Comment by Alizter** [comment]
I've pointed the coq-dpdgraph submodule to my commit which patches it for coq 8.12. Once that commit is merged upstream we can point it to the main repo commits again. This makes all our CI jobs happy, so I think this is ready to merge.

**Comment by spitters** [comment]
You should open an issue here to get it integrated into coq platform,
that would hopefully prevent it from breaking each time.
https://github.com/MSoegtropIMC/coq-platform/issues

**Comment by Alizter** [comment]
Alright there is a patch in preparation for coq-dpdgraph that should come out soon.

**Comment by Alizter** [comment]
@mikeshulman @JasonGross Anybody able to review?

**Pull request merged**
