### PR TITLE
Bumped coq-HoTT submodule to 8.5pl2, pulling in a few bugfixes.

### PR DESCRIPTION
**Pull request by peterlefanulumsdaine**
Replacement for https://github.com/HoTT/HoTT/pull/826; see discussion there.

### CODE REVIEW

**Comment by peterlefanulumsdaine** [comment]
(Sorry for noise of closing/reopening; just hit the wrong button there.)

**Comment by JasonGross** [comment]
Do we want to continue targeting a single pl, or would it be reasonable to aim for compatibility with both pl1 and pl2?  (I can make Travis check both versions in addition to the submodule, if desired.)

In any case, assuming this is the 8.5pl2 tag and assuming that it builds, LGTM.

**Comment by mikeshulman** [comment]
If it's easy to make Travis check both versions, then we might as well.  That way we'll at least *know* if and when we break pl1 compatibility, and we can decide then whether it's worth trying to maintain.

**Comment by JasonGross** [comment]
Should be pretty easy.  We do it [here](https://github.com/mit-plv/fiat-crypto/blob/master/.travis.yml), for example.

**Comment by peterlefanulumsdaine** [comment]
Agreed with Mike — maintaining dual compatibility seems worth doing at least as long as it remains easy.

**Pull request merged**
