### PR TITLE
New lemmas and some cleanup.

### PR DESCRIPTION
**Pull request by andreaslyn**
This will be used to develop a univalent category of algebras and homomorphisms for a signature.

### CODE REVIEW

**Comment by spitters** [comment]
LGTM.
I think we want to avoid simpl and use cbn instead.

**Comment by mikeshulman** [comment]
LGTM too.  Is there a reason to use cbn in cases where simpl works?  I thought it was just that cbn usually works better.

**Comment by Alizter** [comment]
@mikeshulman I think simpl does a few more things than cbn, and I guess this means cbn is more consistent. That's the impression I got anyway.

**Comment by spitters** [comment]
"The cbn tactic is claimed to be a more principled, faster and more predictable replacement for simpl."
https://coq.inria.fr/refman/proof-engine/tactics.html

I thought simpl would be deprecated, but it appears that it's not as strong as that.

**Comment by andreaslyn** [comment]
I am now using `cbn` instead of `simpl`. In my experience `cbn` can be significantly faster when there is a lot to reduce.

**Pull request merged**
