### PR TITLE
Adapt to coq/coq#13188 (Default disable automatic generalization of Instance type)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by JasonGross — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Not sure why it's failing on master

**Comment by SkySkimmer** [comment]
Whatever issue is making CI fail can't be related, can we get this merged? @JasonGross

**Comment by Alizter** [comment]
I don't have time to look into this right now but why was this merged with a failing job?

**Comment by JasonGross** [comment]
The error on the CI job is
```
error: The following untracked working tree files would be overwritten by checkout:
	kernel/float64.ml
Please move or remove them before you switch branches.
Aborting
Unable to checkout 'c97b82cda0ba4c0b9ad8199658c3a09461f3a8d7' in submodule path 'coq-HoTT'
```
This is bizarre, bit it is definitely unrelated to this PR.  I don't have time to dig into it right now, and this PR was blocking for one of Coq's PRs.  Furthermore I judged that the likelihood of this succeeding on the pinned version but failing on master to be minimal, especially since it needs to work on master for the Coq devs to be happy merging the PR this was blocking

**Pull request merged**
