### PR TITLE
Replace eqp_issig_contr tactic with a lemma

### PR DESCRIPTION
**Pull request by jdchristensen**
The `eqp_issig_contr` tactic for characterizing identity types can be replaced by a lemma.  The advantages of this are that the type of the lemma provides clear documentation for what it can do, and the lemma only needs to be proved once, instead of each time the tactic is used.  I also split out part of the functionality into another lemma which might be of independent use.  All the uses of the old tactic have been converted to the new lemma, just by adding a `revert` and an `apply`.

### CODE REVIEW

**Comment by mikeshulman** [comment]
Why is the `revert` necessary?

**Comment by jdchristensen** [comment]
If instead of

  `revert G H; apply (eqp_issig_contr issig_group)`

you try

  `apply (eqp_issig_contr issig_group G H)`

then Coq doesn't infer the implicit type family.

**Comment by Alizter** [comment]
So `apply` can be pretty dumb when it comes to arguments. `rapply` should work if not `serapply` definitely will.

**Comment by jdchristensen** [comment]
No, that's not the issue.  Even if you do something like

  `refine (eqp_issig_contr issig_group _ _ G H).`

Coq isn't able to figure out the type family given just one instance of it.  But

  `revert G H; apply eqp_issig_contr issig_group`

is easy to type and works.

**Comment by Alizter** [comment]
@jdchristensen Intriguing! I tried it myself and it looks like coq really fails to unify when there isn't a `forall a0 a1` around. It's even weirder that it can't unify with the arguments explicitly given!

**Comment by Alizter** [comment]
I'm happy with this PR, but I would also like to suggest a name change. What about changing `eqp_issig_contr` to `equiv_path_issig_contr`? Of course, if @mikeshulman is happy with it.

**Comment by jdchristensen** [comment]
Ok, I made those changes.

**Comment by mikeshulman** [comment]
Taking @Alizter's comment as an approval, I'll go ahead and merge.  BTW, thanks for all these contributions, Dan!  I look forward to seeing the whole development you're working on; are you considering submitting it to the library as well?

**Comment by jdchristensen** [comment]
Yes, the things I'm working on are intended for the library, but will take some time.

**Comment by Alizter** [comment]
Thanks Dan!

**Pull request merged**
