### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by JasonGross**
This will tell dependabot to create PRs to update our submodules and github actions versions

### CODE REVIEW

**Comment by Alizter** [comment]
So this will create a PR for each submodule? Should we do https://github.com/HoTT/HoTT/pull/1590 first?

**Comment by JasonGross** [comment]
```
npm does not support Node.js v10.24.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
/usr/local/lib/node_modules/npm/lib/npm.js:32
```

Hmmmm

**Comment by JasonGross** [comment]
> So this will create a PR for each submodule? Should we do #1590 first?

Yes, and sure

**Comment by JasonGross** [comment]
Shall we merge this now?  (The ci failure is unrelated)

**Pull request merged**
