### PR TITLE
ProofGeneral variable for Coq

### PR DESCRIPTION
**Pull request by tymmym**
Changing `proof-prog-name` has no effect for me. Maybe we should use `coq-prog-name`?

### CODE REVIEW

**Comment by mikeshulman** [comment]
Yes, it looks like `coq-prog-name` is used by coq PG to set `proof-prog-name`.  I'm not sure why this is, but I agree it's `coq-prog-name` we should be telling the user to set.

However, we also have a `.dir-locals.el` file that's supposed to automatically set `coq-prog-name` correctly.  Does it not work for you?

**Comment by tymmym** [comment]
I assume it works fine for browsing existing theories. But in my case after installation I created a file and tried `Require Import HoTT`.

**Comment by mikeshulman** [comment]
Creating a new file in `theories/` it works fine for me; a dir-locals file should also apply to new files created in a directory.

**Comment by tymmym** [comment]
I created a file outside HoTT repository.

**Comment by mikeshulman** [comment]
Oh, ok.  Was setting `coq-prog-name` sufficient to make it work?

**Comment by mikeshulman** [comment]
It might be good to also mention in these instructions that this should only be necessary if you're outside the repo directory.

**Comment by tymmym** [comment]
Yes, it was sufficient.

**Comment by mikeshulman** [comment]
Thanks!  LGTM.

**Pull request merged**
