### PR TITLE
Monoidal Category Theory

### PR DESCRIPTION
**Pull request by patrick-nicodemus**
I propose to create a monoidal category theory folder. I have supplied a definition of a monoidal category to begin with.

### CODE REVIEW

**Comment by Alizter** [comment]
Let's get #1645 merged then you can rebase on master and force push here, which should fix the CI. I'm a bit busy today, but tomorrow I can take a look.

**Comment by Alizter** [comment]
Try rebasing now.

**Comment by Alizter** [comment]
I see that you have been using your own master branch on your fork. This is generally discouraged since it gets confusing to have  a branch called master, especially when somebody else checks it out.

I would do:
```sh
git checkout -b monoidal-cat
```

Which will checkout a new branch at your commit called "monoidal-cat".

Next I would push this to your fork, since you have no branch in origin called "monoidal-cat" yet, you should pass the "-u" option and do "git push -u". It should say new branch created after perhaps asking for your github login depending how you set it up.

If you don't have an upstream remote, then add one by doing `git remote add upstream git@github.com:HoTT/HoTT.git`, followed by `git fetch --all` which will fetch the knowledge of the repos on github.

Next, in order to rebase on the master branch of the main HoTT repo, you should do this following:
```sh
git rebase upstream/master
```

If the rebase complains about something, post what it says here and I can help you through it. Otherwise you should now have your original commits sitting above the latest master of the HoTT repo.

Now you want to update the branch you have on github. In order to do this do
```
git push
```

After that is done, you will have a branch on Github with the commits you intend to merge. You will have to unfortunately close this PR and open a new one since it is a different branch.

Let me know if you have any questions.

**Comment by patrick-nicodemus** [comment]
Thanks very much, I am new to this.

**Pull request closed without merging**
